# Generated by Django 3.2.8 on 2021-10-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_contracttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10, verbose_name='nombre')),
            ],
        ),
    ]
