# Generated by Django 3.2.8 on 2021-10-20 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_operationprogramtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationProgramStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Nombre')),
                ('time_threshold', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='access_to_ops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='access_to_organizations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='access_to_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.TextField(max_length=5, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operationprogramtype',
            name='name',
            field=models.TextField(max_length=10, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('default_counterpart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='rest_api.organization')),
                ('default_user_contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to=settings.AUTH_USER_MODEL)),
                ('op_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='rest_api.operationprogramtype')),
            ],
        ),
        migrations.CreateModel(
            name='OperationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(unique=True, verbose_name='Fecha de inicio')),
                ('op_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='rest_api.operationprogramtype')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rest_api.organization'),
        ),
    ]
