# Generated by Django 3.2.8 on 2021-11-02 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0003_changeoprequest_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeoprequest",
            name="op_release_date",
            field=models.DateField(
                default=datetime.datetime(2021, 11, 2, 21, 10, 12, 175397, tzinfo=utc),
                verbose_name="Fecha de implementación",
            ),
            preserve_default=False,
        ),
    ]
