# Generated by Django 3.2.8 on 2021-11-02 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_changeoprequest_op_release_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterPartContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counter_part_contacts",
                        to="rest_api.organization",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counter_part_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contacto de contraparte",
                    ),
                ),
            ],
        ),
    ]
