# Generated by Django 3.2.8 on 2021-10-20 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20211020_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_request', to='rest_api.contracttype')),
                ('counterpart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_request', to='rest_api.organization')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_requests', to=settings.AUTH_USER_MODEL)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_requests', to='rest_api.operationprogram')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_requests', to='rest_api.operationprogramstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOPRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_request_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('change_op_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rest_api.changeoprequest')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rest_api.operationprogramstatus')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='rest_api.operationprogramstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OPChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('change_op_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op_change_logs', to='rest_api.changeoprequest')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op_change_logs', to=settings.AUTH_USER_MODEL)),
                ('new_op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rest_api.operationprogram')),
                ('previous_op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rest_api.operationprogram')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOPRequestMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Archivo')),
                ('change_op_request_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_request_message_files', to='rest_api.changeoprequestmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOPRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Archivo')),
                ('change_op_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_request_files', to='rest_api.changeoprequest')),
            ],
        ),
    ]
