# Generated by Django 3.2.8 on 2021-11-03 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0005_counterpartcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("contract_administrator", "Administrador de contrato"),
                    ("planning_technician", "Técnico de planificación"),
                    ("prosecutor", "Fiscal"),
                ],
                default="Técnico de planificación",
                max_length=30,
                verbose_name="Rol",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OPChangeDateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_data", models.JSONField(verbose_name="Datos anteriores")),
                ("new_data", models.JSONField(verbose_name="Datos nuevos")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="op_change_date_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
        ),
    ]
