# Generated by Django 3.2.8 on 2021-11-03 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0008_auto_20211103_1546"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opchangedatalog",
            options={
                "verbose_name": "Log de cambios de PO",
                "verbose_name_plural": "Logs de cambios de PO",
            },
        ),
        migrations.AddField(
            model_name="opchangedatalog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de creación"
            ),
        ),
    ]
