# Generated by Django 3.2.8 on 2021-11-04 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0009_auto_20211103_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterpartcontact",
            name="counter_part_organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counter_part_contact",
                to="rest_api.organization",
                verbose_name="Organización contraparte",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="counterpartcontact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counter_part_contact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacto de contraparte",
            ),
        ),
    ]
