# Generated by Django 3.2.8 on 2021-11-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0010_auto_20211104_2229"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counterpartcontact",
            options={
                "verbose_name": "Contacto de contraparte",
                "verbose_name_plural": "Contactos de contraparte",
            },
        ),
    ]
