# Generated by Django 3.2.8 on 2021-11-04 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0011_alter_counterpartcontact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeoprequestmessage",
            name="change_op_request",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_request_message",
                to="rest_api.changeoprequest",
                verbose_name="Solicitud de cambio de PO",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="changeoprequestmessage",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_request_message",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creador",
            ),
        ),
    ]
