# Generated by Django 3.2.8 on 2021-11-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0012_auto_20211104_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeoprequestmessagefile",
            name="change_op_request",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_request_message_files",
                to="rest_api.changeoprequest",
                verbose_name="Solicitud de cambio de PO",
            ),
            preserve_default=False,
        ),
    ]
