# Generated by Django 3.2.8 on 2021-11-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0013_changeoprequestmessagefile_change_op_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changeoprequestmessagefile",
            name="change_op_request",
        ),
    ]
