# Generated by Django 3.2.8 on 2021-11-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0014_remove_changeoprequestmessagefile_change_op_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="rest_api.user",
                verbose_name="Usuario",
            ),
            preserve_default=False,
        ),
    ]
