# Generated by Django 3.2.8 on 2021-11-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0017_alter_statuslog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opchangelog",
            name="change_op_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="op_change_logs",
                to="rest_api.changeoprequest",
                verbose_name="Solicitud de cambio de PO",
            ),
        ),
    ]
