# Generated by Django 3.2.8 on 2021-11-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0018_alter_opchangelog_change_op_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="change_op_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_request_status_logs",
                to="rest_api.changeoprequest",
                verbose_name="Solicitud de cambio de Programa de Operación",
            ),
        ),
    ]
