# Generated by Django 3.2.8 on 2021-11-17 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0019_alter_statuslog_change_op_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opchangelog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="change_op_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_logs",
                to="rest_api.changeoprequest",
                verbose_name="Solicitud de cambio de Programa de Operación",
            ),
        ),
    ]
