# Generated by Django 3.2.8 on 2021-12-02 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0020_auto_20211117_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="opchangedatalog",
            name="update_deadlines",
            field=models.BooleanField(default=False, verbose_name="Actualiza plazos"),
        ),
        migrations.AlterField(
            model_name="changeoprequestmessage",
            name="change_op_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_request_messages",
                to="rest_api.changeoprequest",
                verbose_name="Solicitud de cambio de PO",
            ),
        ),
        migrations.AlterField(
            model_name="changeoprequestmessage",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_request_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creador",
            ),
        ),
    ]
