# Generated by Django 3.2.8 on 2021-12-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0021_auto_20211202_1757"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opchangedatalog",
            name="update_deadlines",
        ),
        migrations.AddField(
            model_name="opchangelog",
            name="update_deadlines",
            field=models.BooleanField(default=False, verbose_name="Actualiza plazos"),
        ),
    ]
