# Generated by Django 3.2.8 on 2021-12-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0022_auto_20211202_1800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeoprequest",
            name="op",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_requests",
                to="rest_api.operationprogram",
                verbose_name="Programa de Operación",
            ),
        ),
        migrations.AlterField(
            model_name="changeoprequest",
            name="op_release_date",
            field=models.DateField(blank=True, verbose_name="Fecha de implementación"),
        ),
        migrations.AlterField(
            model_name="opchangelog",
            name="new_op",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="rest_api.operationprogram",
                verbose_name="Nuevo Programa de Operación",
            ),
        ),
        migrations.AlterField(
            model_name="opchangelog",
            name="previous_op",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="rest_api.operationprogram",
                verbose_name="Programa de Operación previo",
            ),
        ),
    ]
