# Generated by Django 3.2.8 on 2021-12-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0023_auto_20211203_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opchangelog",
            name="new_op",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="rest_api.operationprogram",
                verbose_name="Nuevo Programa de Operación",
            ),
        ),
        migrations.AlterField(
            model_name="opchangelog",
            name="previous_op",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="rest_api.operationprogram",
                verbose_name="Programa de Operación previo",
            ),
        ),
    ]
