# Generated by Django 3.2.8 on 2021-12-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0024_auto_20211203_1506"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeoprequest",
            name="op",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_requests",
                to="rest_api.operationprogram",
                verbose_name="Programa de Operación",
            ),
        ),
    ]
