# Generated by Django 3.2.8 on 2021-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0025_alter_changeoprequest_op"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeoprequest",
            name="op_release_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de implementación"
            ),
        ),
    ]
