# Generated by Django 3.2.8 on 2021-12-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0026_alter_changeoprequest_op_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeoprequest",
            name="related_requests",
            field=models.ManyToManyField(
                blank=True,
                related_name="_rest_api_changeoprequest_related_requests_+",
                to="rest_api.ChangeOPRequest",
                verbose_name="Solicitudes relacionadas",
            ),
        ),
    ]
