# Generated by Django 3.2.8 on 2022-04-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0029_auto_20220413_1909"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChangeOProcessStatus",
            new_name="ChangeOPProcessStatus",
        ),
        migrations.RenameModel(
            old_name="ChangeOProcessStatusLog",
            new_name="ChangeOPProcessStatusLog",
        ),
    ]
