# Generated by Django 3.2.8 on 2022-04-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0031_changeopprocess_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeopprocess',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rest_api.changeopprocessstatus', verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
