# Generated by Django 3.2.8 on 2022-04-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0032_changeopprocess_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changeopprocess",
            options={
                "verbose_name": "Proceso de cambio de PO",
                "verbose_name_plural": "Procesos de cambio de PO",
            },
        ),
    ]
