# Generated by Django 3.2.8 on 2022-04-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0033_alter_changeopprocess_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeopprocessmessage",
            name="change_op_process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_process_messages",
                to="rest_api.changeopprocess",
                verbose_name="Solicitud de cambio de PO",
            ),
        ),
    ]
