# Generated by Django 3.2.8 on 2022-04-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0034_alter_changeopprocessmessage_change_op_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeopprocessmessagefile",
            name="change_op_process_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_process_message_files",
                to="rest_api.changeopprocessmessage",
                verbose_name="Mensaje de proceso de cambio de Programa de Operación",
            ),
        ),
    ]
