# Generated by Django 3.2.8 on 2022-04-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0035_alter_changeopprocessmessagefile_change_op_process_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeopprocessstatuslog",
            name="change_op_process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_op_status_logs",
                to="rest_api.changeopprocess",
                verbose_name="Proceso de cambio de PO",
            ),
        ),
    ]
