# Generated by Django 3.2.8 on 2022-05-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0038_changeopprocess_op_release_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opchangelog",
            name="change_op_request",
        ),
        migrations.AddField(
            model_name="opchangelog",
            name="change_op_process",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="op_change_logs",
                to="rest_api.changeopprocess",
                verbose_name="Solicitud de cambio de PO",
            ),
            preserve_default=False,
        ),
    ]
