# Generated by Django 3.2.8 on 2022-05-09 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0041_changeoprequestopchangelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeOPRequestReasonChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "change_op_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_op_request_reason_change_logs",
                        to="rest_api.changeoprequest",
                        verbose_name="Solicitud de cambio de PO",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_op_request_reason_change_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creador",
                    ),
                ),
                (
                    "new_op",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rest_api.operationprogram",
                        verbose_name="Razón nueva",
                    ),
                ),
                (
                    "previous_op",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rest_api.operationprogram",
                        verbose_name="Razón previa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de razón de solicitud de cambio de PO",
                "verbose_name_plural": "Logs razón de solicitud de cambio de PO",
            },
        ),
    ]
