# Generated by Django 3.2.8 on 2022-05-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0042_changeoprequestreasonchangelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changeoprequestreasonchangelog",
            name="new_op",
        ),
        migrations.RemoveField(
            model_name="changeoprequestreasonchangelog",
            name="previous_op",
        ),
    ]
