# Generated by Django 3.2.8 on 2022-05-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0043_auto_20220508_2246"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeoprequestreasonchangelog",
            name="new_reason",
            field=models.CharField(
                choices=[
                    ("shortening", "Acortamiento"),
                    ("parameters_adjustment", "Ajuste de Parámetros"),
                    ("capacity_adjustment", "Ajuste de Capacidades"),
                    ("frequency_adjustment", "Ajuste de Frecuencias"),
                    ("operational_adjustment", "Ajuste Operacional"),
                    ("stop_change", "Cambios de Paradas"),
                    ("speed_change", "Cambios de Velocidades"),
                    ("operation_schedule_change", "Cambios Horarios de Operación"),
                    ("round_up_service", "Circunvalar Servicio"),
                    ("delete", "Eliminación"),
                    ("terminal_extension", "Extensión a Terminal"),
                    ("fair_and_or_bike_way", "Feria y/o Ciclorecreovía"),
                    ("fusion", "Fusión"),
                    ("integrated_km", "Km Integrados"),
                    ("path_modification", "Modificación de Trazado"),
                    ("head_modification", "Modificación de Cabezal"),
                    ("new_service", "Nuevo Servicio"),
                    ("bus_typology", "Tipología de Bus"),
                    ("other", "Otros"),
                ],
                default=0,
                max_length=30,
                verbose_name="Motivo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="changeoprequestreasonchangelog",
            name="previous_reason",
            field=models.CharField(
                choices=[
                    ("shortening", "Acortamiento"),
                    ("parameters_adjustment", "Ajuste de Parámetros"),
                    ("capacity_adjustment", "Ajuste de Capacidades"),
                    ("frequency_adjustment", "Ajuste de Frecuencias"),
                    ("operational_adjustment", "Ajuste Operacional"),
                    ("stop_change", "Cambios de Paradas"),
                    ("speed_change", "Cambios de Velocidades"),
                    ("operation_schedule_change", "Cambios Horarios de Operación"),
                    ("round_up_service", "Circunvalar Servicio"),
                    ("delete", "Eliminación"),
                    ("terminal_extension", "Extensión a Terminal"),
                    ("fair_and_or_bike_way", "Feria y/o Ciclorecreovía"),
                    ("fusion", "Fusión"),
                    ("integrated_km", "Km Integrados"),
                    ("path_modification", "Modificación de Trazado"),
                    ("head_modification", "Modificación de Cabezal"),
                    ("new_service", "Nuevo Servicio"),
                    ("bus_typology", "Tipología de Bus"),
                    ("other", "Otros"),
                ],
                default=0,
                max_length=30,
                verbose_name="Motivo",
            ),
            preserve_default=False,
        ),
    ]
