# Generated by Django 3.2.8 on 2022-05-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0044_auto_20220508_2248"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changeopprocessstatuslog",
            options={
                "verbose_name": "Log de estado de proceso",
                "verbose_name_plural": "Logs de estado de proceso",
            },
        ),
    ]
