# Generated by Django 3.2.13 on 2022-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0045_alter_changeopprocessstatuslog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationprogram',
            name='op_type',
            field=models.IntegerField(choices=[(1, 'Base'), (2, 'Modificado'), (3, 'Especial')]),
        ),
        migrations.DeleteModel(
            name='OperationProgramType',
        ),
    ]
