# Generated by Django 3.2.13 on 2022-06-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0046_auto_20220614_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Programa de Operación',
                'verbose_name_plural': 'Tipos de Programa de Operación',
            },
        ),
        migrations.AlterField(
            model_name='operationprogram',
            name='op_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='rest_api.operationprogramtype', verbose_name='Tipo de Programa de Operación'),
        ),
    ]
