# Generated by Django 3.2.13 on 2022-06-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0047_auto_20220615_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterpartcontact',
            old_name='user',
            new_name='counter_part_user',
        ),
    ]
