# Generated by Django 3.2.13 on 2022-06-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0049_remove_counterpartcontact_counter_part_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_counterpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='rest_api.organization', verbose_name='Organización que será contraparte por defecto'),
        ),
    ]
