# Generated by Django 3.2.13 on 2022-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0053_changeoprequest_routes_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_route_code', models.CharField(max_length=30, unique=True, verbose_name='Código transantiago')),
                ('op_route_code', models.CharField(max_length=30, verbose_name='Código de operación')),
                ('user_route_code', models.CharField(max_length=30, null=True, verbose_name='Código de usuario')),
                ('route_type', models.CharField(max_length=30, null=True, verbose_name='Tipo de ruta')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Fecha de creación')),
                ('operator', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'diccionario PO ',
                'verbose_name_plural': 'diccionarios PO',
            },
        ),
    ]
