# Generated by Django 3.2.13 on 2022-06-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0054_routedictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opchangelog',
            name='operation_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='rest_api.operationprogram', verbose_name='Programa de Operación'),
        ),
    ]
