# Generated by Django 3.2.13 on 2022-06-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0055_alter_opchangelog_operation_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeoprequest',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='change_op_requests', to='rest_api.user', verbose_name='Usuario creador del proceso'),
            preserve_default=False,
        ),
    ]
