# Generated by Django 3.2.13 on 2022-06-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0056_changeoprequest_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeoprequest',
            old_name='op',
            new_name='operation_program',
        ),
    ]
