# Generated by Django 3.2.13 on 2022-06-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0057_rename_op_changeoprequest_operation_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeoprequest',
            old_name='routes_related',
            new_name='related_routes',
        ),
        migrations.AlterField(
            model_name='changeopprocesslog',
            name='change_op_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_process_logs', to='rest_api.changeopprocess', verbose_name='Proceso de cambio de PO'),
        ),
        migrations.AlterField(
            model_name='opchangelog',
            name='operation_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op_change_logs', to='rest_api.operationprogram', verbose_name='Programa de Operación'),
        ),
    ]
