# Generated by Django 3.2.13 on 2022-06-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0058_auto_20220620_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeoprequestlog',
            name='change_op_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_requests_logs', to='rest_api.changeoprequest', verbose_name='Solicitud de modificación'),
        ),
    ]
