# Generated by Django 3.2.13 on 2022-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0060_changeopprocessfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeopprocessmessagefile',
            name='filename',
            field=models.CharField(default='filename', max_length=128),
            preserve_default=False,
        ),
    ]
