# Generated by Django 3.2.13 on 2022-06-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0061_changeopprocessmessagefile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeoprequest',
            name='change_op_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_op_requests', to='rest_api.changeopprocess', verbose_name='Proceso de cambio de PO'),
        ),
    ]
