# Generated by Django 3.2.13 on 2022-06-23 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0062_alter_changeoprequest_change_op_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeoprequest',
            name='related_routes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None),
        ),
    ]
