# Generated by Django 3.2.13 on 2022-07-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0066_changeopprocessmessage_related_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeopprocessmessagefile',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
