# Generated by Django 3.2.13 on 2022-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0067_changeopprocessmessagefile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeopprocessmessagefile',
            name='size',
            field=models.IntegerField(help_text='The size, in bytes, of the uploaded file.'),
        ),
    ]
