# Generated by Django 3.2.13 on 2022-07-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0068_alter_changeopprocessmessagefile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeopprocesslog',
            name='type',
            field=models.CharField(choices=[('change_op_request_creation', 'Creación de Solicitud de modificación'), ('change_op_request_update', 'Actualización de Solicitud de modificación'), ('status_change', 'Cambio de estado'), ('op_change', 'Cambio de programa de operación'), ('op_change_with_deadline_updated', 'Cambio de programa de operación con actualización de deadlines')], max_length=50),
        ),
    ]
