# Generated by Django 3.2.13 on 2022-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0069_alter_changeopprocesslog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeoprequestlog',
            name='type',
            field=models.CharField(choices=[('change_op_request_update', 'Actualización de datos'), ('change_op_request_creation', 'Creación de solicitud')], max_length=50),
        ),
    ]
