# Generated by Django 3.2.13 on 2022-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0070_alter_changeoprequestlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeopprocesslog',
            name='type',
            field=models.CharField(choices=[('status_change', 'Cambio de estado'), ('op_change', 'Cambio de programa de operación'), ('op_change_with_deadline_updated', 'Cambio de programa de operación con actualización de deadlines')], max_length=50),
        ),
    ]
