# Generated by Django 3.2.14 on 2022-08-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0071_alter_changeopprocesslog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_to_upload_route_dictionary',
            field=models.BooleanField(default=False, verbose_name='Acceso a subir diccionario de servicios'),
        ),
    ]
