# Generated by Django 3.2.14 on 2022-08-06 04:43

from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0072_user_access_to_upload_route_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeopprocessmessagefile',
            name='file',
            field=models.FileField(upload_to=rest_api.models.get_upload_to, verbose_name='Archivo'),
        ),
    ]
