# Generated by Django 3.2.14 on 2022-08-10 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0073_alter_changeopprocessmessagefile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOPProcessDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('change_op_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='rest_api.changeopprocess', verbose_name='Proceso de cambio de PO')),
            ],
        ),
    ]
