# Generated by Django 3.2.14 on 2022-08-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0075_changeopprocessdeadline_operation_program_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeopprocessdeadline',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite'),
        ),
    ]
