# Generated by Django 3.2.14 on 2022-08-15 18:27

from django.db import migrations


def delete_some_rows(apps, scheme_editor):
    model = apps.get_model('rest_api', 'RouteDictionary')
    model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0076_alter_changeopprocessdeadline_deadline'),
    ]

    operations = [
        migrations.RunPython(delete_some_rows),
    ]
