# Generated by Django 3.2.14 on 2022-08-15 18:23
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0077_auto_20220815_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routedictionary',
            name='auth_route_code',
        ),
        migrations.RemoveField(
            model_name='routedictionary',
            name='op_route_code',
        ),
        migrations.RemoveField(
            model_name='routedictionary',
            name='route_type',
        ),
        migrations.AddField(
            model_name='routedictionary',
            name='service_name',
            field=models.CharField(default='test', max_length=30, verbose_name='Nombre servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routedictionary',
            name='ts_code',
            field=models.CharField(default='test', max_length=30, unique=True, verbose_name='Código TS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routedictionary',
            name='user_route_code',
            field=models.CharField(default='test', max_length=30, verbose_name='Código de usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routedictionary',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routedictionary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
