# Generated by Django 3.2.14 on 2022-08-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0078_auto_20220815_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedictionary',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Fecha de actualización'),
        ),
    ]
