# Generated by Django 3.2.14 on 2022-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0079_alter_routedictionary_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedictionary',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Nombre servicio'),
        ),
    ]
