# Generated by Django 3.2.14 on 2022-08-15 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0080_alter_routedictionary_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedictionary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
