# Generated by Django 3.2.14 on 2022-08-15 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0081_alter_routedictionary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedictionary',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización'),
        ),
    ]
