version: '3.7'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - certs_vhost:/etc/nginx/vhost.d
      - certs_html:/usr/share/nginx/html
    depends_on:
      - nginx
    networks:
      - nginx_proxy_network

  letsencrypt:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      - DEFAULT_EMAIL:cephei.1313@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - certs_vhost:/etc/nginx/vhost.d
      - certs_html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy

  nginx:
    restart: always
    environment:
      - VIRTUAL_HOST=opct.adatrap.cl
      - LETSENCRYPT_HOST=opct.adatrap.cl
    networks:
      - nginx_proxy_network

  web:
    restart: always

  worker:
    restart: always

  cache:
    restart: always

  db:
    restart: always

networks:
  nginx_proxy_network:
    driver: bridge

volumes:
  acme:
  certs:
  certs_vhost:
  certs_html:
