version: '3.7'

services:
  web:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: webserver
    volumes:
      - static_volume_opct:/app/static
      - media_volume_opct:/app/media
    env_file:
      - ./docker_env
    depends_on:
      - db
      - cache
    networks:
      - nginx_network
      - database_network
      - cache_network

  worker:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: worker
    volumes:
      - static_volume_opct:/app/static
      - media_volume_opct:/app/media
    env_file:
      - ./docker_env
    depends_on:
      - cache
      - db
    networks:
      - database_network
      - cache_network

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/NginxDockerfile
    ports:
      - 8000:80
    volumes:
      - static_volume_opct:/app/static
      - media_volume_opct:/app/media
    depends_on:
      - web
    networks:
      - nginx_network

  cache:
    restart: always
    image: redis:latest
    networks:
      - cache_network

  db:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - postgres_opct:/var/lib/postgresql/data/
    env_file:
      - ./docker_db_env
    networks:
      - cache_network
      - database_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  cache_network:
    driver: bridge

volumes:
  postgres_opct:
  static_volume_opct:
  media_volume_opct:
